Namespaces:
  =: io.murano.opaas.puppet
  std: io.murano
  res: io.murano.resources
  sys: io.murano.system
  puppet: io.murano.opaas.puppet

Name: SystemConfig

Methods:
  installOnTheNode:
    Arguments:
      instance:
        Contract: $.class(puppet:PuppetInstance)
    Body:
      - $resources: new(sys:Resources)
      - $template: $resources.yaml('SystemConfig.template')
      - $instance.agent.call($template, $resources)
